[mgr]
show_hidden = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" }
]
view = [
  { run = 'feh-dir-start-at "$@"', orphan = true, for = "unix" }
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { name = "*.txt", use = "edit" },
  { mime = "image/*", use = "view" },
  { name = "*.png", use = "view" },
  { name = "*.jpg", use = "view" },
  { name = "*.jpeg", use = "view" },
  { name = "*.gif", use = "view" },
  { name = "*.svg", use = "view" },
  { name = "*.webp", use = "view" }
]

