version: '3'
services:
  warp:
    image: warp-container
    environment:
      - DISPLAY=:0
      - XDG_RUNTIME_DIR=/tmp
    user: "${UID}:${GID}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /:/mnt
      - /dev/dri:/dev/dri

